//! 引擎：构造（全部内部表的初值）。

use super::*;

impl<'a> Engine<'a> {
    pub fn new(h: &'a Hierarchy<'a>, cp: &'a ClassPath, man: &'a Manifest, hw: &'a Handwritten) -> Self {
        let mut e = Engine {
            ctx: Ctx {
                h,
                cp,
                man,
                hw,
                consts: Default::default(),
                domains: Default::default(),
                calls: Default::default(),
                fields: Default::default(),
                guards: RefCell::new(memo::Guards::new()),
                catalog: Default::default(),
                loaders: Default::default(),
                selectors: Default::default(),
                fvals: Default::default(),
                rvals: Default::default(),
                fopen: Default::default(),
                fopen_names: Default::default(),
                fhw: Default::default(),
                fhw_names: Default::default(),
                fopen_all: Cell::new(false),
                deser: Cell::new(false),
                fdeps: Default::default(),
                rdeps: Default::default(),
                noreturn: Default::default(),
                never: Default::default(),
                objs: Default::default(),
                psums: Default::default(),
                preadonly: Default::default(),
                pwsums: Default::default(),
                punstable: Default::default(),
                pdeps: Default::default(),
                dep_log: Default::default(),
                cevals: Default::default(),
                mrecs: Default::default(),
                mdeps: Default::default(),
                memo_next: Default::default(),
                ceval_depth: Default::default(),
                stats: Default::default(),
            },
            h,
            cp,
            man,
            hw,
            names: Vec::new(),
            ids: HashMap::default(),
            narrow_cache: HashMap::default(),
            sub_rows: Vec::new(),
            classes: IndexMap::default(),
            missing: BTreeMap::new(),
            methods: IndexMap::default(),
            mbase: HashMap::default(),
            fields: IndexMap::default(),
            graph: FlowGraph::default(),
            g: BTreeSet::new(),
            g_sub: HashMap::default(),
            lambdas: HashMap::default(),
            hwobjs: HashMap::default(),
            arrays: HashMap::default(),
            empty_arrays: HashMap::default(),
            escaped: HashSet::default(),
            self_fields: HashMap::default(),
            obj_fields: HashMap::default(),
            objs: HashMap::default(),
            obj_chain: HashMap::default(),
            containers: HashMap::default(),
            dflt_alloc: HashSet::default(),
            factories: HashMap::default(),
            forwarders: HashMap::default(),
            inited: IndexMap::default(),
            dispatch: BTreeMap::new(),
            recv_sites: HashSet::default(),
            direct_virtual_sites: HashSet::default(),
            pvals: HashMap::default(),
            ptaint: HashSet::default(),
            pstr: Default::default(),
            hubs: Vec::new(),
            hub_ids: HashMap::default(),
            hubs_by_open: BTreeMap::new(),
            hub_sites: BTreeMap::new(),
            hub_last: HashMap::default(),
            gathers: Vec::new(),
            gather_ids: HashMap::default(),
            gather_last: HashMap::default(),
            vm_hubs: HashSet::default(),
            vm_targets: HashSet::default(),
            vm_open_hubs: HashSet::default(),
            vm_rcall_hubs: HashMap::default(),
            vm_hub_targets: HashMap::default(),
            rcall_members: Vec::new(),
            rcall_ix: HashMap::default(),
            rcall_bound: HashMap::default(),
            rcall_entries: HashMap::default(),
            rcall_sites: HashSet::default(),
            rcall_pooled: HashSet::default(),
            rcall_m2h: false,
            rcall_conv: HashSet::default(),
            rcall_conv_pending: HashMap::default(),
            rcall_conv_seen: HashSet::default(),
            rcall_stats: Default::default(),
            callers: HashMap::default(),
            call_vals: None,
            unresolved: BTreeSet::new(),
            refs: BTreeSet::new(),
            mref_keys: HashMap::default(),
            indy_models: BTreeMap::new(),
            sigpoly_sites: BTreeSet::new(),
            cold_cut: false,
            mwork: VecDeque::new(),
            in_mwork: HashSet::default(),
            watch: HashMap::default(),
            swork: VecDeque::new(),
            in_swork: HashSet::default(),
            cur_site: None,
            dispatched: HashMap::default(),
            hub_linked: HashMap::default(),
            hub_lsent: HashMap::default(),
            recv_done: HashMap::default(),
            lambda_done: HashMap::default(),
            lcalls: Vec::new(),
            cur_call: None,
            call_watch: HashMap::default(),
            mirror_watch: HashMap::default(),
            shared: HashMap::default(),
            open_calls: BTreeMap::new(),
            cwork: VecDeque::new(),
            in_cwork: HashSet::default(),
            hw_site_ids: HashMap::default(),
            hw_self_copies: HashSet::default(),
            hw_sites: Vec::new(),
            hw_reads: HashMap::default(),
            hw_offsets: HashMap::default(),
            ref_fields: HashMap::default(),
            hw_writes: HashMap::default(),
            poly_writes: Vec::new(),
            poly_reads: Vec::new(),
            open_statics: Vec::new(),
            mirror_writes: HashMap::default(),
            offset_waits: HashMap::default(),
            offset_read_waits: HashMap::default(),
            static_offset_live: false,
            static_base_waits: Vec::new(),
            fwork: VecDeque::new(),
            xreaders: HashMap::default(),
            lookup_top: HashSet::default(),
            lookup_partial: false,
            flow_batch: super::worklist::FLOW_BATCH,
            open_methods: BTreeMap::new(),
            open_sites: BTreeMap::new(),
            pending_types: BTreeMap::new(),
            lambda_stack: HashSet::default(),
            mirrors: HashMap::default(),
            prim_mirror: None,
            cs: Default::default(),
            mirror_of: Vec::new(),
            mflows: HashMap::default(),
            mflow_seen: HashSet::default(),
            mirror_open: BTreeMap::new(),
            mirror_open_seen: HashSet::default(),
            synth_mirror: None,
            enum_recv: HashMap::default(),
            rpending: Vec::new(),
            enumerated: BTreeSet::new(),
            reflect_names: HashMap::default(),
            named_ctors: BTreeSet::new(),
            invokable: BTreeSet::new(),
            lwraps: HashMap::default(),
            reflect_gaps: BTreeSet::new(),
            reflect_members: BTreeSet::new(),
            reflect_fields: BTreeSet::new(),
            reflect_field_names: BTreeSet::new(),
            field_strs: HashMap::default(),
            hw_written: BTreeSet::new(),
            fwriter_live: false,
            cuts: Default::default(),
            probes: None,
            spret: Default::default(),
            rmwrap: Default::default(),
            fenum_pending: BTreeSet::new(),
            fenum_serial: BTreeSet::new(),
            field_enum_gaps: BTreeSet::new(),
            hw_written_names: BTreeSet::new(),
            hw_read_names: BTreeMap::new(),
            snake_index: std::cell::OnceCell::new(),
            vm_rules_fired: 0,
            hw_static_reads: HashSet::default(),
            seeds: SeedState::default(),
            flow_src: diag::NO_SRC,
            open_inj: HashMap::default(),
            concrete: Default::default(),
        };
        e.concrete_init();
        e
    }
}
