//! 引擎：构造（全部内部表的初值）。

use super::*;

impl<'a> Engine<'a> {
    pub fn new(h: &'a Hierarchy<'a>, cp: &'a ClassPath, man: &'a Manifest, hw: &'a Handwritten) -> Self {
        Engine {
            ctx: Ctx {
                h,
                cp,
                man,
                hw,
                consts: Default::default(),
                domains: Default::default(),
                calls: Default::default(),
                fields: Default::default(),
                guards: RefCell::new(memo::Guards::new()),
                selectors: Default::default(),
                fvals: Default::default(),
                rvals: Default::default(),
                fopen: Default::default(),
                fopen_names: Default::default(),
                fopen_all: Cell::new(false),
                deser: Cell::new(false),
                fdeps: Default::default(),
                rdeps: Default::default(),
                noreturn: Default::default(),
                never: Default::default(),
                objs: Default::default(),
                psums: Default::default(),
                punstable: Default::default(),
                pdeps: Default::default(),
                cevals: Default::default(),
                ceval_reads: Default::default(),
                ceval_depth: Default::default(),
                stats: Default::default(),
            },
            h,
            cp,
            man,
            hw,
            names: Vec::new(),
            ids: HashMap::default(),
            sub_cache: HashMap::default(),
            narrow_cache: HashMap::default(),
            sub_rows: Vec::new(),
            classes: IndexMap::new(),
            missing: BTreeMap::new(),
            methods: IndexMap::new(),
            mbase: HashMap::default(),
            fields: IndexMap::new(),
            graph: FlowGraph::default(),
            g: BTreeSet::new(),
            g_sub: HashMap::default(),
            lambdas: HashMap::default(),
            hwobjs: HashMap::default(),
            arrays: HashMap::default(),
            empty_arrays: HashMap::default(),
            escaped: HashSet::default(),
            self_fields: HashMap::default(),
            obj_fields: HashMap::default(),
            objs: HashMap::default(),
            obj_chain: HashMap::default(),
            containers: HashMap::default(),
            factories: HashMap::default(),
            forwarders: HashMap::default(),
            inited: IndexMap::new(),
            dispatch: BTreeMap::new(),
            recv_sites: HashSet::default(),
            pvals: HashMap::default(),
            pstr: Default::default(),
            hubs: Vec::new(),
            hub_ids: HashMap::default(),
            hubs_by_open: BTreeMap::new(),
            hub_sites: BTreeMap::new(),
            hub_last: HashMap::default(),
            vm_hubs: HashSet::default(),
            callers: HashMap::default(),
            call_vals: None,
            unresolved: BTreeSet::new(),
            refs: BTreeSet::new(),
            indy_models: BTreeMap::new(),
            cold_cut: false,
            mwork: VecDeque::new(),
            in_mwork: HashSet::default(),
            watch: HashMap::default(),
            swork: VecDeque::new(),
            in_swork: HashSet::default(),
            cur_site: None,
            dispatched: HashMap::default(),
            hub_linked: HashMap::default(),
            hub_lsent: HashMap::default(),
            hub_ssent: HashMap::default(),
            recv_done: HashMap::default(),
            lambda_done: HashMap::default(),
            lcalls: Vec::new(),
            cur_call: None,
            call_watch: HashMap::default(),
            mirror_watch: HashMap::default(),
            open_calls: BTreeMap::new(),
            cwork: VecDeque::new(),
            in_cwork: HashSet::default(),
            hw_site_ids: HashMap::default(),
            hw_sites: Vec::new(),
            hw_reads: HashMap::default(),
            ref_fields: HashMap::default(),
            hw_writes: HashMap::default(),
            poly_writes: Vec::new(),
            open_statics: Vec::new(),
            fwork: VecDeque::new(),
            xreaders: HashMap::default(),
            lookup_top: HashSet::default(),
            lookup_partial: false,
            flow_batch: super::worklist::FLOW_BATCH,
            open_methods: BTreeMap::new(),
            open_sites: BTreeMap::new(),
            pending_types: BTreeMap::new(),
            lambda_stack: HashSet::default(),
            mirrors: HashMap::default(),
            mirror_of: Vec::new(),
            mflows: HashMap::default(),
            mflow_seen: HashSet::default(),
            enum_recv: HashMap::default(),
            rpending: Vec::new(),
            enumerated: BTreeSet::new(),
            reflect_names: HashMap::default(),
            named_ctors: BTreeSet::new(),
            invokable: BTreeSet::new(),
            reflect_gaps: BTreeSet::new(),
            class_init: Default::default(),
            reflect_members: BTreeSet::new(),
            hw_written: BTreeSet::new(),
            fwriter_live: false,
            spret: Default::default(),
            fenum_pending: BTreeSet::new(),
            hw_written_names: BTreeSet::new(),
            hw_read_names: BTreeMap::new(),
            snake_index: None,
            seeds: SeedState::default(),
            via_flow: false,
            open_inj: HashMap::default(),
        }
    }
}
