[package]
name = "emit"
version.workspace = true
edition.workspace = true

[dependencies]
classfile.workspace = true
resolve.workspace = true
ty.workspace = true
input.workspace = true
regex.workspace = true
crc32fast.workspace = true
indexmap.workspace = true
closure.workspace = true
toml.workspace = true

[dev-dependencies]
serde_json.workspace = true
