[package]
name = "driver"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rava"
path = "src/main.rs"

[dependencies]
classfile.workspace = true
resolve.workspace = true
serde_json.workspace = true
closure.workspace = true
emit.workspace = true
ir.workspace = true
input.workspace = true
ty.workspace = true
mimalloc.workspace = true
