[package]
name = "user"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "user"
path = "src/main.rs"

[[bin]]
name = "test_array_list_rust"
path = "../../tests/test_array_list_rust.rs"

[dependencies]
java_runtime    = { path = "../java_runtime" }
java_rta_macros = { path = "../java_rta_macros" }
jdk_classes     = { path = "../jdk_classes" }
